In [1]:
# Hello, World! of PRyMordial
import PRyM.PRyM_main as PRyMmain
%time myPRyM = PRyMmain.PRyMclass()

CPU times: user 6.78 s, sys: 62 ms, total: 6.84 s
Wall time: 6.92 s


In [2]:
# [Neff , Ω_ν h^2 × 10^6 (rel), ∑ m_ν / (Ω_ν h^2) [eV], YP (CMB), YP (BBN), D/H × 10^5, 3He/H × 10^5, 7Li/H × 10^10]
myPRyM.PRyMresults()

array([ 3.04438852,  5.69940717, 93.03360798,  0.24556139,  0.2468873 ,
        2.46225365,  1.04204994,  5.42356155])

In [3]:
# Individual call for each observable
myPRyM.Neff(),myPRyM.Omeganurel(),myPRyM.Omeganunonrel(),myPRyM.YPCMB(),myPRyM.YPBBN(),myPRyM.DoH(),myPRyM.He3oH(),myPRyM.Li7oH(),

(np.float64(3.044388520277093),
 np.float64(5.699407167709801),
 np.float64(0.010748803811036461),
 np.float64(0.24556139207051403),
 np.float64(0.2468872961883013),
 np.float64(2.462253649187069e-05),
 np.float64(1.04204993836121e-05),
 np.float64(5.42356154576855e-10))

In [4]:
# Change of input parameter
import PRyM.PRyM_init as PRyMini
PRyMini.tau_n = 879 # s
myPRyMnewtau = PRyMmain.PRyMclass()

In [5]:
# Results with new neutron lifetime
myPRyMnewtau.PRyMresults()

array([ 3.04438852,  5.69940717, 93.03360798,  0.24568329,  0.24700963,
        2.46123924,  1.04209406,  5.42618103])

In [6]:
# Change of nuclear rates
PRyMini.nacreii_flag = True
PRyMini.ReloadKeyRates()
myPRyMnacreii = PRyMmain.PRyMclass()

In [7]:
# Results with NACRE-II key nuclear rates
myPRyMnacreii.PRyMresults()

array([ 3.04438852,  5.69940717, 93.03360798,  0.24560228,  0.24692834,
        2.53332718,  1.04628913,  5.26140204])

In [8]:
# Use small nuclear network comprising key rates for YP and D/H
PRyMini.smallnet_flag = True
%time PRyMmain.PRyMclass().PRyMresults()

CPU times: user 4.48 s, sys: 20.9 ms, total: 4.5 s
Wall time: 4.58 s


array([ 3.04438852,  5.69940717, 93.03360798,  0.24559572,  0.24692175,
        2.52850084,  1.04615251,  5.32563037])

In [9]:
############################################
# Code to reproduce Figure 2 of 2307.07061 #
############################################
# Restore neutron lifetime of PDG 2023
PRyMini.tau_n = 878.4 # s
# Include incomplete decoupling in a(T)
aTid_flag = True
# Recompute the background from scratch
PRyMini.compute_bckg_flag = True
# Save the background in PRyMrates/thermo
PRyMini.save_bckg_flag = True
# Recompute n <--> p rates from scratch
PRyMini.compute_nTOp_flag = True
# Save n <--> p rates in PRyMrates/nTOp
PRyMini.save_nTOp_flag = True
# Include only key rates in nuclear network
PRyMini.smallnet_flag = True
# NACRE II compilation for key rates
PRyMini.nacreii_flag = True
# compute PRyM observables
YP,DoHx1e5,He3oHx1e5,Li7oHx1e10 = PRyMmain.PRyMclass().PRyMresults()[4:8]

In [10]:
# Change in etab does not require to recompute background and p <--> n
PRyMini.compute_bckg_flag = False
PRyMini.save_bckg_flag = False
PRyMini.compute_nTOp_flag = False
PRyMini.save_nTOp_flag = False
# Compute PRyMordial obs will now be faster!
%time YP,DoHx1e5,He3oHx1e5,Li7oHx1e10 = PRyMmain.PRyMclass().PRyMresults()[4:8]

CPU times: user 840 ms, sys: 4.62 ms, total: 845 ms
Wall time: 848 ms


In [11]:
# PDG plot
npoints = 20
import numpy as np
etabvec = np.logspace(-10,-9,npoints)
# Initialization of array of observables
YP_vec, DoH_vec, He3oH_vec, Li7oH_vec = np.zeros((4,npoints))
for i in range(npoints):
    # Update value of baryon-to-photon ratio
    PRyMini.eta0b = etabvec[i]
    # Store obs computed for the new eta
    YP_vec[i], DoH_vec[i], He3oH_vec[i], Li7oH_vec[i] = PRyMmain.PRyMclass().PRyMresults()[4:8]

In [12]:
# Sample of array values for Figure 2 in 2307.07061
# Figure 2 obtained w/ 50 points + PDG 2023 inputs + large nuclear network
print("etab10 : ",etabvec*1e+10)
print("YP : ",YP_vec)
print("DoH : ",DoH_vec)

etab10 :  [ 1.          1.12883789  1.27427499  1.43844989  1.62377674  1.83298071
  2.06913808  2.33572147  2.6366509   2.97635144  3.35981829  3.79269019
  4.2813324   4.83293024  5.45559478  6.15848211  6.95192796  7.8475997
  8.8586679  10.        ]
YP :  [0.22160966 0.22436958 0.22684115 0.22906949 0.2311058  0.23296969
 0.23469653 0.23630145 0.23783247 0.23927865 0.2406507  0.2419748
 0.24324814 0.24449203 0.24569994 0.24688064 0.2480388  0.24916722
 0.25029471 0.25139583]
DoH :  [46.3128514  37.96092114 31.12851634 25.47584431 20.86102153 17.08792982
 14.05693442 11.56335541  9.54998619  7.87418431  6.52338528  5.39185588
  4.45082538  3.68145726  3.03373873  2.48951755  2.03478354  1.65601479
  1.3356304   1.06332693]


In [13]:
############################################
# Code to reproduce Figure 3 of 2307.07061 #
############################################
# SM MC run
num_it = 80 # toy MC ... 10K used for Figure 3 w/ large network
import numpy as np
YP_vec, DoH_vec, He3oH_vec, Li7oH_vec = np.zeros((4,num_it))
# Baryon eta from Planck 18 (no BBN prior)
mean_eta0b = PRyMini.Omegabh2_to_eta0b*0.02230
std_eta0b = PRyMini.Omegabh2_to_eta0b*2*1.e-4
# Neutron lifetime from PDG 2023
mean_tau_n = 878.4 # s
std_tau_n = 0.5 # s

In [14]:
# Compute primordial abundances at each iteration
def ComputeAbundances(i):
    # Settings to speed up the SM MC
    PRyMini.recompute_bckg = False
    PRyMini.recompute_nTOp_rates = False
    # Small network used: Set to False for a more reliable prediction of Li7
    PRyMini.smallnet_flag = True
    PRyMini.num_reactions = 12 # for the large network, set this to be 63
    # Gaussian prior on baryon-to-photon ratio
    PRyMini.eta0b = np.random.normal(mean_eta0b,std_eta0b)
    # Gaussian prior on neutron lifetime
    PRyMini.tau_n = np.random.normal(mean_tau_n,std_tau_n)
    # Log-normal prior on nuclear rates
    # For the large network, many more ... see PRyM_init.py
    PRyMini.p_npdg,PRyMini.p_dpHe3g,PRyMini.p_ddHe3n,PRyMini.p_ddtp,PRyMini.p_tpag,PRyMini.p_tdan,PRyMini.p_taLi7g,PRyMini.p_He3ntp,PRyMini.p_He3dap,PRyMini.p_He3aBe7g,PRyMini.p_Be7nLi7p,PRyMini.p_Li7paa = np.random.normal(0,1,PRyMini.num_reactions)
    # Adopt NACRE II compilation for key rates
    PRyMini.nacreii_flag = True
    PRyMini.ReloadKeyRates()
    return PRyMmain.PRyMclass().PRyMresults()[4:8]

In [18]:
# Parallelizing w/ joblib + multiprocessing
from joblib import Parallel, delayed
import multiprocessing
num_cpu = int(multiprocessing.cpu_count())
FinalAbundances = Parallel(n_jobs = num_cpu)(delayed(ComputeAbundances)((i)) 
for i in range(num_it))
YP_vec, DoH_vec, He3oH_vec, Li7oH_vec = np.array(FinalAbundances).transpose()

ModuleNotFoundError: No module named 'joblib'

In [16]:
# Statistics for primordial helium-4 mass fraction
print("Mean", np.mean(YP_vec), " +-", np.std(YP_vec))
np.quantile(YP_vec,[0.16,0.5,0.84])

Mean 0.0  +- 0.0


array([0., 0., 0.])

In [17]:
# Statistics for primordial deuterium relative H number density
print("Mean", np.mean(DoH_vec), " +-", np.std(DoH_vec))
np.quantile(DoH_vec,[0.16,0.5,0.84])

Mean 0.0  +- 0.0


array([0., 0., 0.])